language: en
pipeline:
- name: SpacyNLP
  model: en_core_web_lg
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: SpacyEntityExtractor
  dimensions:
  - PERSON
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 50
  entity_recognition: true
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
policies:
- name: MemoizationPolicy
  max_history: 8
- name: RulePolicy
  core_fallback_threshold: 0.1
  core_fallback_action_name: action_default_fallback_end_dialog
  enable_fallback_prediction: true
assistant_id: 20230331-134224-creamy-trust
